services:
  - type: web
    name: joint-intelligence
    env: static
    staticPublishPath: /
    buildCommand: ""
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
